#2724
osrf/gazebo pull request #2725
Opened 2020-05-03 15:52 UTC by nlamprian

It has been observed that `OnPublishComplete` can run before `result` is checked in `SendMessage`. In that case, the `pubIds` entry is deleted by `OnPublishComplete`, and then it's recreated in `SendMessage`. This [blocks publication of any future messages](https://github.com/osrf/gazebo/blob/gazebo9/gazebo/transport/Publisher.cc#L165), thus rendering the publisher unusable.

The fix guards access to `pubIds` in `SendMessage`, and it processes the `pubIds` entry only if it still exists.

2020-05-28 17:19 UTC, chapulina commented
Thanks for the PR, @nlamprian . Do you think it would be possible to write a test that exercises the fix?

2020-05-28 20:52 UTC, nlamprian commented
Oof, this will require some effort. I'll need to familiarize myself with the full implementation to understand how to trigger the conditions. I'll give it a try.

2020-06-27 00:03 UTC, nlamprian commented
The unit test is added. It successfully reproduces the error. Basically, for the error to show up, there have to be callbacks in the `Publication`. A callback is added by a subscription to the `Publication`, which, in this case, happens in the `ConnectionManager` with a `SubscriptionTransport`. It's still not clear to me how everything around all of this works, but nonetheless, I replicated the conditions in the test. There, it can be seen that the first message is sent and received, but the second one is not.

2020-09-08 13:36 UTC, nlamprian commented
May I please ask for an update on this? Is there something holding back the review? The publisher continues to be a problem for me, and I would hope to see it fixed soon.

2020-09-09 00:52 UTC, chapulina commented
@osrf-jenkins run tests

Thank you for the contribution and the test, it looks good to me. Let's just run a round of CI to make sure everything is ok.

2020-09-21 17:01 UTC, chapulina commented
@osrf-jenkins run tests again?

2020-09-22 17:50 UTC, chapulina requested changes

2020-09-22 17:50 UTC, chapulina commented on test/regression/2724_failing_publisher.cc
> +  NodePtr node = boost::make_shared<Node>();
This is failing compilation on CI:

```
/var/lib/jenkins/workspace/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-nvidia/gazebo/test/regression/2724_failing_publisher.cc:67:18: error: ���make_shared��� is not a member of ���boost���
   NodePtr node = boost::make_shared<Node>();
```

I think you may need to use `new` with the supported boost version.

2020-09-27 02:10 UTC, nlamprian commented
@osrf-jenkins run tests

2020-09-28 19:46 UTC, chapulina commented
@osrf-jenkins run tests

2020-09-30 06:43 UTC, chapulina approved these changes
The fix and test look good and CI is happy :+1:

2020-09-30 06:43 UTC, merged