[Gazebo 9] Backport Added ignition common profiler
osrf/gazebo pull request #2783
Opened 2020-07-09 16:59 UTC by ahcorde

This PR is a backport of this other PR https://github.com/osrf/gazebo/pull/2776

Gazebo 9 uses `ign-common1`, in this version of ignition common the profiler is not implemented yet. To backport this functionality into `ign-common` requires to also backport `components` into `ign-cmake0`. I have talked with @chapulina and it makes sense to include the profiler code inside the Gazebo code. In particular I have added this code in `gazebo utils` where the other profiler ( Diagnostic) it's also located.

2020-07-29 07:26 UTC, ahcorde commented
We should "merge" this PR if we want to keep the history with the Gazebo 11 branch instead of "squash and merge".

2020-07-29 19:26 UTC, iche033 commented
[jenkins build](https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/261/console) caught a cmake error and I was able to reproduce it locally. If `-DENABLE_PROFILER=1` is not specified when running cmake, I get this:

```
CMake Error at cmake/GazeboUtils.cmake:133 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  gazebo_profiler
Call Stack (most recent call first):
  gazebo/util/CMakeLists.txt:179 (gz_install_library)
```

2020-08-03 01:57 UTC, chapulina requested changes
>  I have added this code in gazebo utils

It looks like you created a new library, `gazebo_profiler`, instead of adding it to `gazebo_utils`. Is there a reason for that? Creating a new library comes with extra overhead.


---

The examples are failing to build, see the results for the `EXAMPLE_examples_build` test:

```
375: In file included from /usr/include/gazebo-9/gazebo/common/common.hh:18:0,
375:                  from /usr/include/gazebo-9/gazebo/gazebo_client.hh:23,
375:                  from /var/lib/jenkins/workspace/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/gazebo/examples/stand_alone/transporter/transporter.cc:18:
375: /usr/include/gazebo-9/gazebo/common/Event.hh:32:39: fatal error: gazebo/profiler/Profiler.hh: No such file or directory
```

We need to make sure that it's possible to compile against Gazebo even if the profiler is not enabled.

2020-08-03 01:57 UTC, chapulina commented on gazebo/profiler/CMakeLists.txt
> +  gz_install_includes("profiler" Profiler.hh)
Can we not install this header? If we do, we'll need to go through a tick-tock deprecation cycle. I think for Gazebo <= 9 we can keep the profiler internal, and for Gazebo 11 + we expose the `ign-common` profiler as we're doing for `gazebo_ros_pkgs`.

2020-08-03 01:57 UTC, chapulina commented on gazebo/common/CMakeLists.txt
> +  ${IGNITION-COMMON_LIBRARIES}
I think this can be removed.

2020-08-03 01:57 UTC, chapulina commented on gazebo/profiler/Profiler.hh
> +#define IGNITION_COMMON_PROFILER_HH_
```suggestion
#define GAZEBO_COMMON_PROFILER_HH_
```

There are other instances too

2020-08-03 01:57 UTC, chapulina commented on gazebo/profiler/Profiler.hh
> +#ifndef IGN_PROFILER_ENABLE
Can we change all of these from `IGN` to `GZ`? Just to be safe in case the 2 of them ever get mixed in the same project.

2020-08-03 01:57 UTC, chapulina commented on worlds/profiler.world
> +<?xml version="1.0" ?>
Could you comment on what this world is supposed to be demonstrating?

2020-08-11 21:54 UTC, chapulina commented
This was superceded by #2813, which includes this PR.

2020-08-11 21:54 UTC, closed without merging