ODEJoint: don't SetStiffnessDamping for gearbox
osrf/gazebo pull request #3169
Opened 2022-02-07 21:54 UTC by scpeters

The Gearbox joint does not support the stiffness and damping parameters, so exit ODEJoint::SetStiffnessDamping early if for Gearbox joints.

Without this change, simulations including a gearbox joint stream a prohibitive amount of unnecessary messages to a log file with complaints about APIs that are unsupported by the Gearbox joint. To confirm, load the [variable_gearbox_plugin.world](https://github.com/osrf/gazebo/blob/gazebo11/worlds/variable_gearbox_plugin.world) and check the size of the `~/.gazebo/server-11345/default.log` file after running for a few seconds of simulation time.

2022-02-07 21:59 UTC, jacobperron approved these changes

2022-02-07 22:09 UTC, adityapande-1995 approved these changes

2022-02-07 22:11 UTC, adityapande-1995 commented
Changes look good but testing locally

2022-02-07 23:19 UTC, adityapande-1995 commented
I'm still seeing this message spammed in the log : 
```
(1644275888 431658517) GetAngle not implemented for gearbox
(1644275888 431669354) SetForce not implemented for gearbox
(1644275888 431680096) GetVelocity not implemented for gearbox
(1644275888 431690652) GetAngle not implemented for gearbox
(1644275888 431701085) SetForce not implemented for gearbox
(1644275888 432632467) GetVelocity not implemented for gearbox
(1644275888 432644740) GetAngle not implemented for gearbox
(1644275888 432655591) SetForce not implemented for gearbox
(1644275888 432666309) GetVelocity not implemented for gearbox
(1644275888 432676917) GetAngle not implemented for gearbox
```

2022-02-07 23:26 UTC, adityapande-1995 requested changes
I'm still seeing this message spammed in the log :
```
(1644275888 431658517) GetAngle not implemented for gearbox
(1644275888 431669354) SetForce not implemented for gearbox
(1644275888 431680096) GetVelocity not implemented for gearbox
(1644275888 431690652) GetAngle not implemented for gearbox
(1644275888 431701085) SetForce not implemented for gearbox
(1644275888 432632467) GetVelocity not implemented for gearbox
(1644275888 432644740) GetAngle not implemented for gearbox
(1644275888 432655591) SetForce not implemented for gearbox
(1644275888 432666309) GetVelocity not implemented for gearbox
(1644275888 432676917) GetAngle not implemented for gearbox
```
Maybe we also need to add similar quick return logic for SetForce, GetVelocity, GetAngle methods.

2022-02-07 23:56 UTC, scpeters commented
> I'm still seeing this message spammed in the log :
> 
> ```
> (1644275888 431658517) GetAngle not implemented for gearbox
> (1644275888 431669354) SetForce not implemented for gearbox
> (1644275888 431680096) GetVelocity not implemented for gearbox
> (1644275888 431690652) GetAngle not implemented for gearbox
> (1644275888 431701085) SetForce not implemented for gearbox
> (1644275888 432632467) GetVelocity not implemented for gearbox
> (1644275888 432644740) GetAngle not implemented for gearbox
> (1644275888 432655591) SetForce not implemented for gearbox
> (1644275888 432666309) GetVelocity not implemented for gearbox
> (1644275888 432676917) GetAngle not implemented for gearbox
> ```
> 
> Maybe we also need to add similar quick return logic for SetForce, GetVelocity, GetAngle methods.

this branch is supposed to prevent exactly those messages. Can you confirm that you build this branch in a colcon workspace, have sourced the setup file and are running this version of gazebo? I don't see those messages in my build

2022-02-08 02:54 UTC, adityapande-1995 commented
Sorry my bad. Changed branch, deleted old log, new logs look like this : 
```
Gazebo multi-robot simulator, version 11.10.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org


(1644288733 879771529) [Msg] Waiting for master.
(1644288733 889884401) [Msg] Connected to gazebo master @ http://127.0.0.1:11345
(1644288733 889935470) [Msg] Publicized address: 10.0.0.51
(1644288734 456266202) [Msg] Loading world file [/home/aditya/Desktop/temp/temp.sdf]
(1644288734 540333227) ODEGearboxJoint::SetAnchor not implemented.
(1644288734 540350048) SetParam not implemented for gearbox
(1644288734 540358960) SetParam not implemented for gearbox
(1644288734 540367204) SetParam not implemented for gearbox
(1644288734 540381436) SetParam not implemented for gearbox
(1644288734 540392023) SetParam not implemented for gearbox
(1644288734 540400392) SetParam not implemented for gearbox
(1644288734 540413271) GetAngle not implemented for gearbox
(1644288734 540422350) GetParam not implemented for gearbox
(1644288734 540429344) GetAngle not implemented for gearbox
(1644288734 540437105) GetParam not implemented for gearbox
(1644288734 540505780) ODESliderJoint::SetAnchor not implemented.
(1644288734 541033538) Init world[default]
(1644288735 844828758) GetAngle not implemented for gearbox
(1644288735 844843413) GetParam not implemented for gearbox
(1644288735 844854596) GetAngle not implemented for gearbox
(1644288735 844867124) GetParam not implemented for gearbox
(1644288736 315827585) GetAngle not implemented for gearbox
(1644288736 315838643) GetParam not implemented for gearbox
(1644288736 315846844) GetAngle not implemented for gearbox
(1644288736 315855687) GetParam not implemented for gearbox
```

2022-02-08 03:02 UTC, adityapande-1995 approved these changes

2022-02-08 17:49 UTC, merged